### PR TITLE
rename instances of legacy Switch_Keyboard

### PR DESCRIPTION
**Pull request by perigoso**
The library name was changed recently, so some links and references were outdated.

Ihis is untested, i don't think i broke anything though.

### CODE REVIEW

**Comment by adamws** [comment]
thanks for pointing this out, I did quick fix here https://github.com/adamws/keyboard-tools/commit/109a7e836707a53e53d38f95dacef81c0c505338 and will update other references shortly.

**Comment by perigoso** [comment]
I was unaware you had uncommitted work, i rebased on top of your last commits

**Comment by adamws** [comment]
appreciate it, but there has been changes required here https://github.com/adamws/kle2netlist/commit/915dce2709a4de44a92f921db9e63e6700823026 as well - I will carry on from here ;)

**Comment by adamws** [comment]
done here https://github.com/adamws/keyboard-tools/commit/0578505b2be092037aef8675349bdd33d4cb97dc

**Pull request closed without merging**
